# Generated by Django 6.0.4 on 2026-04-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(max_length=200),
        ),
    ]
